### PR TITLE
PICARD-730: use credited as name in relationships if any

### PR DESCRIPTION
**Pull request by zas**
http://tickets.musicbrainz.org/browse/PICARD-730

### CODE REVIEW

**Comment by phw** [comment]
Looks great, clean and simple.I just used it for actual tagging and did what I expected.

**Comment by zas** [comment]
> Looks great, clean and simple.I just used it for actual tagging and did what I expected.

I was wondering if it needs a separated option or no, what do you think ?

**Comment by phw** [comment]
> I was wondering if it needs a separated option or no, what do you think ?

I was actually thinking about that, too, while testing. First I thought the options need separation, but it is basically really the same functionality. Separating it into "Use standardized artist names for release and track credits" and "Use standardized artist names for relationships" is IMHO more confusing than it helps. But otherwise I have no strong opinion.

But I found something else that should be changed. For the non AR credits the translation is preferred. So if you have enabled both the translation and standardized names Picard first tries to translate and only if there is no translation it uses the standardized artist name (see https://github.com/zas/picard/blob/picard-730-credited-as/picard/mbxml.py#L173). I find this quite convenient, as I would like to use standardized names if possible, but I want to translate e.g. kyrillic names.

At least the behaviour should be consistent in both cases.

**Comment by zas** [comment]
> But I found something else that should be changed. For the non AR credits the translation is preferred. So if you have enabled both the translation and standardized names Picard first tries to translate and only if there is no translation it uses the standardized artist name (see https://github.com/zas/picard/blob/picard-730-credited-as/picard/mbxml.py#L173). I find this quite convenient, as I would like to use standardized names if possible, but I want to translate e.g. kyrillic names.

I'm not sure to understand, the thing is that the "credited as" "artist" isn't translatable, it isn't even an artist node or alias, just a string, so we only have the choice betwen showing it or no.
When "credited as" isn't used, translation occurs as it should (https://github.com/zas/picard/blob/picard-730-credited-as/picard/mbxml.py#L79).

So, user may want either:
- use artist as is
- use translated artist (if possible)
- use "credited as" value (fixed)

So perhaps instead of replacing artist name by credited as value, we could just use: credited_as (artist|artist_translated), ie. "Lord Seth (Jonas Renkse)".
In this particular example from the link you gave in http://tickets.musicbrainz.org/browse/PICARD-730, https://musicbrainz.org/release/cd4fe34a-7a9e-412f-82db-aa2097a3d5a3 the credited as value already exists as an artist (https://musicbrainz.org/artist/f4f2428f-374f-4440-a38f-cc966ab05bde), so i think instead of crediting Jonas Renkse as Lord Seth, one could have credited Lord Seth (artist/f4f2428f).

Just tell me exactly what you expect (in your case, you seem to say that if a translation is available for the artist (and translation enabled) it should override the credited as option).

That said, i may just merge this PR as is, and see what happens, we can add its own option for this feature later, or even change it on the basis of dev version feedback.

**Comment by phw** [comment]
That's not what I meant. Compare the following code.


This is how the artist credits in `artist_credit_from_node` works:
```
a = credit.artist[0]
translated, translated_sort = _translate_artist_node(a)
if translated != a.name[0].text:
    name = translated
elif 'name' in credit.children and not standardize_artists:
    name = credit.name[0].text
else:
    name = a.name[0].text
```

And this your new code for the AR credits:
```
artist = relation.artist[0]
value, valuesort = _translate_artist_node(artist)
if 'target_credit' in relation.children and not standardize_artists:
    credited_as = relation.target_credit[0].text
    if credited_as:
        value, valuesort = credited_as, credited_as
```

Both first translate the artist name. But the old code uses the translation if there is one and only use the credits when no translation happened (either because the option is disabled or there is simply no translation available). Your new code always replaces the translation with the credits if possible. Different order of precedence, this is the only difference. So I would change it to something like this:

```
artist = relation.artist[0]
value, valuesort = _translate_artist_node(artist)
if value != artist.name[0].text and \
	'target_credit' in relation.children and not standardize_artists:
    credited_as = relation.target_credit[0].text
    if credited_as:
        value, valuesort = credited_as, credited_as
```

**Comment by zas** [comment]
@phw : i updated the code after your comments, check if 6b25a86 does what you expect

**Pull request merged**
