### PR TITLE
Fix bug in oauth when port == 443

### PR DESCRIPTION
**Pull request by Sophist-UK**
`setHost(port)` should be `setPort(Port)` and logic for port == 443 or port != 80 needs fixing.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Fixes [PICARD-766](http://tickets.musicbrainz.org/browse/PICARD-766).

**Comment by mineo** [comment]
-1 from me. That's the third place (the others are https://github.com/musicbrainz/picard/blob/master/picard/browser/filelookup.py#L35 and https://github.com/musicbrainz/picard/blob/master/picard/webservice.py#L192) that this check is performed, it should really be moved to somewhere in picard.util

**Comment by Sophist-UK** [comment]
I agree with @mineo's sentiment - not the least because some of these make their own calls to MB services and avoid the rate limiting code.

But my intent here is simply to fix a bug rather than to remediate existing code - and I don't have the time right now to rationalise this.

So I would suggest that this small PR is merged to provide the use with a quick fix, and that someone else then takes on the remediation.

**Comment by mineo** [comment]
Fair enough, I'll add a pull request for putting the code in one place later.

**Pull request merged**
