### PR TITLE
Remove conversion to lower case

### PR DESCRIPTION
**Pull request by Sophist-UK**
If user wants these in lower case they can add a tagger script and use $lower to make this change.

Obviously much easier to remove case than to determine when and how to add case back in.

### CODE REVIEW

**Comment by phw** [comment]
In general I would agree with this, but the change as it is will cause some existing tagger scripting and also probably external tools to fail. I am especially concerned that this changes the values written to the tags on which third party tools may rely. Maybe do this change as you have done here, but lowercase the tags before writing them to the files.

Also this needs changes in some other places:

1. Update the tests that test for the old behavior
2. Update the renaming examples in `ui/options/renaming.py`

**Comment by Sophist-UK** [comment]
I am unclear why these tags were made lower case in the first place (unless it is a Unix thing :-) ). The purpose of this change was to avoid loss of detail and to keep the data the same as shown on MB.

Personally I doubt that other tools will rely on case and in any case other tagging tools like Jaikoz might not use lower case. If such tools do rely on case then perhaps they should be doing the lower case conversion themselves.

So whiolst this might cause some minor backwards compatibilities, I would be in favour of doing this.

I can certainly update fix the tests and rename examples but I am loath to spend time on these if the PR is going to be rejected - so if I can get an indication that the PR is acceptable in principle, I will do this work.

**Comment by mwiencek** [comment]
I don't see any technical reason to make this backwards-incompatible change. I'm sure there are people performing string comparisons against these.

And there seems to be a good reason for it to me, to ensure the values don't depend on any arbitrary casing (sentence, title) chosen by MB.

**Comment by Sophist-UK** [comment]
@mwiencek has made a good point. So I am closing this.

**Comment by mwiencek** [comment]
> P.S. The fields I changed are all fixed lists of MB attributes and so case is not arbitrary.

I mean that there's not any important reason they use sentence case, and some types are inconsistent, e.g. label types use title case. So the case is "fixed," but arbitrary (and "fixed" is in quotes because there have been cases where we've renamed types, though it's rare).  So people who want to "add case back" are probably better off deciding what case they want and using `.capitalize()` or `.title()`. :)

It was a mistake for MB to ever return strings as constant identifiers. In the future I'd like all the types to have MBIDs, not just link and link attribute types.

**Pull request closed without merging**
