### PR TITLE
Add a -V/--long-version command-line option, display Qt version

### PR DESCRIPTION
**Pull request by zas**
- keep versions sorted, use OrderedDict
- add -V/--long-version command-line option
- add Qt version in the list of versions
- update About page

Fixes http://tickets.musicbrainz.org/browse/PICARD-734

capture du 2015-06-29 10 38 02
capture du 2015-06-29 10 37 27

### CODE REVIEW

**Comment by Freso** [comment]
Perhaps Git revision could be saved somewhere somehow during setup.py and echoed with --long-version as well? Not sure at all how feasible this is, but I have often thought that the "F.O.OdevX" version string isn't much good for those of regularly "building"/installing/updating Picard from Git.

**Comment by Freso** [comment]
But apart from that, looks good at a glance. :+1:

**Comment by zas** [comment]
> I have often thought that the "F.O.OdevX" version string isn't much good for those of regularly "building"/installing/updating Picard from Git.

Yes, there is one advantage over git revision, numbered versions ease upgrading (they are ordered).
But yes, adding the git revision would be a nice extra, i'll think about it.

**Comment by zas** [comment]
https://gist.github.com/mina86/8782771 is interesting
We could just use git tag to set versions (which is much better than modifying source file for that)
```bash
$> git tag -s v1.4.1
$> python version.py
1.4.1
$> git describe --long
v1.4.1-0-g243643e
```

**Comment by Freso** [comment]
I'm pretty sure we're already setting tags though: https://github.com/musicbrainz/picard/releases :wink:

The AUR picard-git PKGBUILD is doing some trickery to make the `git describe --long` output behave well with PKGBUILD versioning: https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=picard-git&id=1411c1f3eb4656c8a14eec917870d4e3e09b3c5f#n19

**Comment by zas** [comment]
After some thoughs, using version from git needs some additionnal work, and isn't immediatly related to this PR, so i will just merge it as is and postpone the git thing: http://tickets.musicbrainz.org/browse/PICARD-735

**Pull request merged**
