### PR TITLE
Ignore special tracks for completeness

### PR DESCRIPTION
**Pull request by phw**
This adds an option to ignore some track types for determining the completeness of an album. This makes it easier for a user to see completed albums and ignore tracks she doesn't care about. Currently the user can choose to ignore:

* Video tracks
* Data tracks
* Pregap tracks
* Silent tracks

In addition this PR adds some more changes to simplify the work with those tracks:

1. Video and data tracks get a different icon instead of the default musical note icon (in case a track is both a data and a video track the video icon gets precedence)
2. Adds a `$is_complete()` tagger script function
3. Sets a `~video` tagger script variable for video tracks
4. Ignored tracks are displayed grayed out, so they are still available for tagging but not as prominent in the listing

This PR will fix [PICARD-514](http://tickets.musicbrainz.org/browse/PICARD-514) and [PICARD-652](http://tickets.musicbrainz.org/browse/PICARD-652)

This PR **is not ready for merging** due to the new icons. I have added icons from the Tango icon set for the track types because this is the icon set the current note icon is taken from. But I think the icons are a) really ugly and b) make the UI way too noisy. But since I am not very talented in designing icons and I am not sure when I will find the time to look for nicer icons with an acceptable license I just publish the code here and **ask you all for help** :)

Some notes about the `$is_complete()` function: This is somewhat similar to the `$isperfectalbum` function @Sophist-UK proposed in [PICARD-637](http://tickets.musicbrainz.org/browse/PICARD-637). But I deliberately decided not to add the special logic of having only one matched file per track. I think this is a different change which should be discussed separately. For me it was important that `$is_complete()` and the visual representation of the completeness are identical.

### CODE REVIEW

**Comment by phw** [comment]
I have played with the icons, please give me some feedback.

New icons, less colorful:
bildschirmfoto vom 2015-01-26 22 53 40

Only the data icon track replaced:
bildschirmfoto vom 2015-01-26 22 59 56

For comparisson the old screenshot from above:
picard-track-types

**Comment by zas** [comment]
I like those in

**Comment by zas** [comment]
@phw : i'm ok to merge it once you'll addressed following comments
https://github.com/musicbrainz/picard/pull/383#discussion_r21511637
https://github.com/musicbrainz/picard/pull/383#discussion_r21512022

**Comment by phw** [comment]
@zas: I've updated the code

**Comment by zas** [comment]
We still need more feedback about new icons, but for me it is ready for merge.

**Comment by reosarevok** [comment]
I prefer the black and white icons in isolation, but dunno how well they work with the rest of the interface. Any of the two options is an improvement though, so both seem good enough.

**Comment by phw** [comment]
Just because I didn't say this: The black icons are also what is currently in this PR as they are the ones I prefer, too :)

**Comment by ianmcorvidae** [comment]
The black-and-white don't seem to match the style of the rest of the interface to me, especially the disc icon, or if not changed the unmatched file icon which currently uses the color notes. A mix of flat and 3D icons seems weird, not to mention a mix of color and non-color, and the black-and-white/flat looks very pre-internet-age-style, or something, to me. The video one maybe contributes to that since really, nobody's using this to print labels for film canisters (and the screen icon matches what's used on mb.org better as well, which may or may not be a goal). So I'd vote for the newer color icons, perhaps ideally with a less flat "binary written on paper" type icon. I do think that's better than the cog for denoting data track, though.

For consideration/comparison, mb.org uses this for data tracks: data track icon

**Comment by Freso** [comment]
+1 to what @ianmcorvidae said.

**Comment by phw** [comment]
I see the issues you have with the flat icons. Well, actually not all :) I don't think these icons look "pre-internet-age-style", rather they are the current popular icon style on many web pages. The colored Tango icons Picard uses are so 90s :P But the real reason I wanted to try those is that they remove visual clutter from the listings and make the main information stand out more while still providing a clear distinction for the track types.

Anyway, when using the data icon from MB this looks like this:

bildschirmfoto vom 2015-02-06 20 51 12

This is probably the version most consistent with both Picards original style and the MB website. I have not pushed those changes yet, but if feedback is positive I will push it and merge this PR.

**Comment by ianmcorvidae** [comment]
I'd maybe support the black-and-white if they were greys rather than pure black-and-white; that's really the thing that makes it feel like I'm looking at Windows 3.1 to me :)

In any case, I like the version with the data track icon from the site if others are fine with that. Perhaps we can move to a flatter icon style in another PR if that's desired, and keep it consistent here.

**Comment by 96187** [comment]
I agree with what reosarevok said. I like the black and white icons, at least in the screenshots here.

Having black and white base icons also leaves open the possibility of adding coloured variants for things like matched tracks, tracks with errors, etc in the future (probably with ticks or exclamation marks so that it's not *just* colour).

The only icon I really didn't like though was the cog.

**Comment by zas** [comment]
> Having black and white base icons also leaves open the possibility of adding coloured variants

Good point. It may be useful in the future.

> that's really the thing that makes it feel like I'm looking at Windows 3.1 to me :)

Windows 3.1 had colorful icons.

**Comment by phw** [comment]
Since the consensus seems to be, that the colored icons are ok and more consistent with current Picard, but the flat icons might be nice to reconsider later, I have merged this PR together with the colored icons. The flat icons are still in the commit history, so if somebody wants to build on this please do.

**Pull request merged**
