### PR TITLE
Add support for id3 TKEY ...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... in support of an AcousticBrainz plugin which will set the TKEY ID3 tag.

### CODE REVIEW

**Comment by phw** [comment]
Would be nice to add this for the other formats, I would follow the Jaikoz implementation, see:

https://docs.google.com/spreadsheets/d/1afugW3R1FRDN-mwt5SQLY4R7aLAu3RqzjN3pR1497Ok/edit?usp=docslist_api

**Comment by Sophist-UK** [comment]
Funny enough, I was just researching this.

**Comment by Sophist-UK** [comment]
Would you mind if I add support for other stuff from this spreadsheet in this same PR?

**Comment by Sophist-UK** [comment]
P.S. Whose spreadsheet is it? Can I get update ability on it in order to make it more complete?

**Comment by phw** [comment]
> Would you mind if I add support for other stuff from this spreadsheet in this same PR?
I would rather add tags case by case than just add everything possible.

> P.S. Whose spreadsheet is it? Can I get update ability on it in order to make it more complete?
Mine, but it is shared with quite a few people. It was edited mostly by me and @ijabz (from Jaikoz). It has a somewhat special color coding: Green means the same tag is supported by both Picard and Jaikoz, orange only Picard, blue only Jaikoz. red there is a conflict.

I have made the file world editable now, so if somebody wants to help please do. I have also updated a few tags that are now supported by Picard, but there are likely still some things not updated in the doc.

**Comment by phw** [comment]
Also here are some pointers to official tag documentation (taken from my notes):

* [ASF / WMA](http://msdn.microsoft.com/en-us/library/ms867702.aspx)
* [ID3](http://id3.org/Developer%20Information)
* [VorbisComment](https://wiki.xiph.org/VorbisComment)
* [APE-Tags](http://wiki.hydrogenaud.io/index.php?title=APE_key)
* MP4: See iTunes Metadata Format Specification. Was available at https://developer.apple.com/, couldn't find it the last time I checked. I have a copy here, but the included license agreement prevents me from sharing it.

**Comment by Sophist-UK** [comment]
I suggest we leave this PR as-is in order to get it merged - and I will update the spreadsheet as much as possible to match.

However, I do suggest that I add all the remaining stuff in a separate PR, as it will enable people to write new plugins but have little other effect (except perhaps to retain tags when they would otherwise be deleted - though there is a whole separate issue relating to the way we handle the saving or deleting of tags which is IMO quite wrong).

**Comment by phw** [comment]
> I suggest we leave this PR as-is in order to get it merged - and I will update the spreadsheet as much as possible to match.

I agree mostly, but I think it makes sense to add the key tag for the other formats.

For all the rest I am not sure if it makes sense to add everything (e.g. I wouldn't add the CustomN tags), but I agree in general that Picard should aim to support more. I guess we can discuss the details in a separate PR :)

**Comment by Sophist-UK** [comment]
Added last night - though I should probably add some tests.

**Comment by Sophist-UK** [comment]
Ok - just syncing with tests added. Then we should be good to go on this.

**Comment by phw** [comment]
> Added last night - though I should probably add some tests.

I must have been blind. Thanks for the tests, I merged it

**Comment by Sophist-UK** [comment]
You may not have been blind - my sync last night may have failed.

**Comment by phw** [comment]
We forgot the issue, so here it is: [PICARD-769](http://tickets.musicbrainz.org/browse/PICARD-769)

**Pull request merged**
