### PR TITLE
Add a way to hide directories older than x hours in multi dirs select…

### PR DESCRIPTION
**Pull request by zas**
…or dialog

This is my own answer to PICARD-690, @dufferzafar proposed another way in https://github.com/musicbrainz/picard/pull/343

This approach is simpler, still only works with the Qt file dialog (not the native one), please test and comment.

capture du 2015-05-22 16 32 31
capture du 2015-05-22 16 32 23
capture du 2015-05-22 16 32 15

See:
- https://github.com/musicbrainz/picard/pull/343
- http://tickets.musicbrainz.org/browse/PICARD-690

### CODE REVIEW

**Comment by mineo** [comment]
Honest question because I never use those dialogs: what's the advantage of this over just sorting by the "Date Modified" column, because I still need to select the still visible folders to only load them - otherwise hitting 'Choose' also loads folders that are not shown because of the filter.

This also seems to break sorting by modification date, as can be seen in the following screenshot, where only the day is used for sorting:
foo

**Comment by zas** [comment]
It doesn't have much advantage over sorting using modification date, but it can be set as an option, so the dialog only show "new" files on opening, and it works in any view mode (ofc).
It is just an anwser to PICARD-690, but i'm not sure myself it is worth.

About the sort issue, i'll investigate when i'll have time.

**Comment by zas** [comment]
> because I never use those dialogs:

@mineo: do you use the 3-panes + drag'n'drop ?

I think it should be the default (Picard on first install shows only 2 panes), and highlighting new files should be done in the tree on the left. I don't use Add folder/files either.

**Comment by mineo** [comment]
Yes, I use the file browser. I think there was some talk somewhere about the future of the file browser one or two years ago, but I don't know where that was :/

**Comment by zas** [comment]
After thinking about it, i don't like this "feature", i close this PR.

**Pull request closed without merging**
